#!/bin/bash
#SBATCH -p high
#SBATCH -N 1   # node count
#SBATCH --ntasks-per-node=16
#SBATCH -t 00:05:00

#module load openmpi/intel-16.0/1.10.2/64
#module load intel/16.0/64/16.0.1.150

# problems with mpiexec/mpirun so use srun
mpiexec ./bin/xgenerate_databases
