#!/bin/bash
#SBATCH -N 2   # node count
#SBATCH --ntasks-per-node=16
#SBATCH -t 00:05:00
# sends mail when process begins, and
# when it ends. Make sure you define your email
# address.
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=dborisov@princeton.edu
# load appropriate compilers/libraries
# module load intel/13.0/64/13.0.1.117
# module load openmpi/intel-13.0/1.6.3/64
#cd /scratch/network/dborisov/specfem3d
#cd /home/dborisov/packages/specfem3d
# problems with mpiexec/mpirun so use srun
mpiexec -n 32 ./bin/xspecfem3D
